version: '3.8'

services:
  quitaddictionbot:
    build: .
    container_name: quitaddictionbot
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./db:/app/db
      - ./logs:/app/logs # Si vous gardez aussi le changement de logs
      - ./config:/app/config
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"